services:
  frontend:
    image: ghcr.io/xitcoin-org/blockscout-frontend:v2.10.3@sha256:4c9384b7e9a2cc38f69766e89ef7c37252612a86f38a18f4ffeff2da26cbd9cc
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_OTHER_LINKS: '[{"text":"XTC (Cronos)","url":"https://explorer.cronos.com/address/0xE45FE733BC8617FA6DAC8437FC44B5FFFA949991"}]'
      NEXT_PUBLIC_GAS_TRACKER_ENABLED: "false"
      NEXT_PUBLIC_WEB3_WALLETS: '["metamask"]'
      NEXT_PUBLIC_NETWORK_LOGO: "https://raw.githubusercontent.com/xitcoin-org/brand/main/assets/png/standard/xitcoin-symbol-500.png"
      NEXT_PUBLIC_NETWORK_ICON: "https://raw.githubusercontent.com/xitcoin-org/brand/main/assets/png/standard/xitcoin-symbol-200.png"
      FAVICON_MASTER_URL: "https://raw.githubusercontent.com/xitcoin-org/brand/main/assets/png/standard/xitcoin-symbol-500.png"
      NEXT_PUBLIC_HOMEPAGE_STATS: '["total_blocks","average_block_time","total_txs","wallet_addresses"]'
      NEXT_PUBLIC_AD_BANNER_PROVIDER: "none"
      NEXT_PUBLIC_API_HOST: evm-explorer-testnet.xitchain.com
      NEXT_PUBLIC_API_PROTOCOL: https
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_API_DOCS_TABS: '["rest_api"]'
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
      NEXT_PUBLIC_APP_HOST: evm-explorer-testnet.xitchain.com
      NEXT_PUBLIC_APP_PROTOCOL: https
      NEXT_PUBLIC_NETWORK_NAME: Xitcoin Testnet
      NEXT_PUBLIC_NETWORK_SHORT_NAME: Xitcoin Testnet
      NEXT_PUBLIC_NETWORK_ID: "101089"
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: Xitcoin
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: XTC
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18"
      NEXT_PUBLIC_IS_TESTNET: "true"
    ports:
      - "127.0.0.1:14001:3000"
